const counties = [
  "ALBANY",
  // "BRONX",
  // "BROOME",
  // "CATTARAUGUS",
  // "CLINTON",
  // "COLUMBIA",
  // "DUTCHESS",
  // "ERIE",
  // "ESSEX",
  // "FRANKLIN",
  // "FULTON",
  // "GREENE",
  // "HERKIMER",
  // "JEFFERSON",
  // "KINGS",
  // "LIVINGSTON",
  // "MONROE",
  // "MONTGOMERY",
  // "N/A - Out of State",
  // "NASSAU",
  // "NEW YORK",
  // "NIAGARA",
  // "NONE",
  // "ONEIDA",
  // "ONONDAGA",
  // "ORANGE",
  // "OSWEGO",
  // "OTSEGO",
  // "PUTNAM",
  // "QUEENS",
  // "RENSSELAER",
  // "RICHMOND",
  // "ROCKLAND",
  // "SARATOGA",
  // "SCHENECTADY",
  // "SUFFOLK",
  // "TOMPKINS",
  // "ULSTER",
  // "WARREN",
  // "WESTCHESTER",
  // "WYOMING",
  // "YATES",
]

module.exports = counties